target_server:
  hosts:
    192.168.88.240:
      ansible_user: "app"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_ssh_private_key_file: "/home/{{ username }}/.ssh/id_ed25519"
      ansible_port: 22
