---
- name: Change sshd port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port '
    line: 'Port {{ new_ssh_port }}'
    state: present

- name: Permit protocol 1
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'Protocol 2'
    create: yes

- name: Permit DebianBanner
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'DebianBanner no'
    create: yes


- name: Permit root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin '
    line: 'PermitRootLogin no'
    state: present

- name: Permit empty passwords
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitEmpyPasswords '
    line: 'PermitEmptyPasswords no'
    state: present

- name: Permit X11Forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?X11Forwarding '
    line: 'X11Forwarding no'
    state: present

- name: Change default banner
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Banner '
    line: 'Banner /etc/issue.net'
    state: present

- name: Remove issue.net
  become: yes
  ansible.builtin.file:
    state: absent
    path: /etc/issue.net

- name: Create clear issue.net
  become: yes
  ansible.builtin.file:
    state: touch
    path: /etc/issue.net

- name: Permit password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication '
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart SSH
# tasks file for set-ssh-settings
